name: Python Test Workflow

on:
  push:
    branches:
      - main
      - 27-python_unit-test-case
  pull_request:
    branches:
      - main
      - 27-python_unit-test-case

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pandas pytest tzlocal

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}  
        run: |
          pytest ./python/tests/test_tbe_file_operations.py 
